### ISSUE TITLE
Not compatible with Android Studio 4.0

### ISSUE THREAD

**Issue by neokree** [Lillls/json2dart#1]
Hi 

Today I upgraded my Android Studio to 4.0, and I realized that the plugin is not supported for this version. It will be supported? This plugin greatly improve the speed of development during API definition. 

My current Android Studio installation.
```
Android Studio 4.0
Build #AI-193.6911.18.40.6514223, built on May 20, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.5
```

**Comment by Lillls** [comment]
Hi
Sorry for taking so long to reply to you. Thanks for your issue and it is the first issue I received. Very glad to help you.I will update it to compatible with Android Studio 4.0

**Comment by neokree** [comment]
Thank you Lillls

**Comment by Lillls** [comment]
Hi,The plugin has been submitted for moderation. The request will be processed within two business days.You can manual install 'build/lib/jar' if you don't want to wait.
